### ISSUE TITLE
Improve readme for KFG repo

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#105]
Continuation of issue #52

**Comment by seekanddefine** [comment]
That's ok! I had some ideas but nothing ready to print. This looks amazing!   
  
I will take a closer look.

**Comment by avidrucker** [comment]
> That's ok! I had some ideas but nothing ready to print. This looks amazing! 
> 
> I will take a closer look.

I'd love to hear your feedback, and you're also welcome to simply edit the document as you see fit. This would also be a fantastic file to practice doing "Pull Requests" on 😉

Please feel free to close this issue, throw it in the icebox, or put it in a future milestone to readdress.
