### ISSUE TITLE
Can I connect with other learners that are on the same learning journey?

### ISSUE THREAD

**Issue by dfirebaugh** [knowledge-for-good/knowledgeforgood#111]
Maybe find a study group or ask questions to someone that recently learned something I'm trying to learn.

**Comment by avidrucker** [comment]
> Maybe find a study group or ask questions to someone that recently learned something I'm trying to learn.

The answer is yes. Both myself and @seekanddefine have access to a bunch of different learning communities, as I am sure do you. I think it's important to be able to find community, in both peers, mentors, groups, and events.

@dfirebaugh Have you wished in the past or recently for more community around a particular skill or technology? Also, do you have any suggestions or recommendations on how to go about introducing people to communities?
