### ISSUE TITLE
We host a meditation session for KFG

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#116]
- [x] Why do we want to host meditation sessions?
- [x] Do we want to focus our efforts more on a different intentional practice, and why or why not?
- [x] What are our challenges / blockers in attempting to host (& be present for) events?

**Comment by avidrucker** [comment]
Sunday at 10am EST/EDT I think was the time we agreed upon.

**Comment by seekanddefine** [comment]
Knowledge For Good: Community Practice  
Sunday, August 1 · 11:00am – 12:00pm  
Google Meet joining info  
Video call link: https://meet.google.com/jsq-kgpg-hrs

**Comment by seekanddefine** [comment]
I would like to host meditation sessions because it's an activity I enjoy doing with others. Meditation reduces my stress. Much more than that it increases my focus, calms my anxiety, boosts my productivity, and expands my capability to practice compassion. In my past life the office was the source of my greatest stress. I think we can build a healthier collective by consistently providing opportunities for anyone interested to join us in mindful practices like meditation.

**Comment by seekanddefine** [comment]
I think it would be fun to try different practices together to learn more about each other and to also try new things. Maybe we can try new things together and offer wisdom in the process.

**Comment by seekanddefine** [comment]
Challenges/blockers so far: busy schedules, family taking priority, overwhelm, organization around getting things started. 

We had our first session last week where we meditated silently together. We ended up starting a little later but that worked out great. The first session we ended up cancelling, so it was great to meet. I look forward to next week.

**Comment by seekanddefine** [comment]
@avidrucker I'm going to go ahead and close this but feel free to reopen and/or add your own thoughts about how it went and what you might like to see in the future please! For next week I am planning on leading and sticking with 60 minutes. All are invited to offer suggestions for practices or take a turn leading.

**Comment by avidrucker** [comment]
> I would like to host meditation sessions because it's an activity I enjoy doing with others. Meditation reduces my stress. Much more than that it increases my focus, calms my anxiety, boosts my productivity, and expands my capability to practice compassion. In my past life the office was the source of my greatest stress. I think we can build a healthier collective by consistently providing opportunities for anyone interested to join us in mindful practices like meditation.

I believe I could benefit from (a) more (consistent) meditation (practice). Thank you @seekanddefine for sharing your reflection, I appreciate and admire your experience and wisdom.

**Comment by avidrucker** [comment]
Note: No one besides me showed for yesterday's meditation session. I propose we confirm two or more attendees, otherwise we reschedule/cancel. How does that sound to you @seekanddefine @caryfado ?

**Comment by seekanddefine** [comment]
We've had some wonderful meditation sessions! We have also had a little bit of back and forth with schedules and finding the right time to host this. I think we are now on for Sunday evening. Is that right @avidrucker ? Or would you like to discuss a brand new recurring time?
