### ISSUE TITLE
Do we need deadlines, dates of completion, "time-bounded" goals, or similar to work effectively? why/not

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#175]

**Comment by avidrucker** [comment]
It strikes me that some people might benefit from due dates more than others, and some people might find "submit by" dates/times to be stressful... I wonder what alternatives there are to help us stay focused and also productive, or perhaps we need to change our mindset / worldview on focus / productivity...

**Comment by seekanddefine** [comment]
It looks like most startups take 6-8 to get established and figure out some funding. How might this give us info to build goals a couple months out when we are ready to do that?

**Comment by seekanddefine** [comment]
Yes, I believe it was 6-8 months! I'm going to go ahead and close this now.
