### ISSUE TITLE
Spend 15 min to locate video file

### ISSUE THREAD

**Issue by seekanddefine** [knowledge-for-good/knowledgeforgood#186]

**Comment by seekanddefine** [comment]
Hi I spent 30 min trying to find the video and had no luck. @avidrucker Would you mind taking a peak in your files please? 

Time spent with notes can be found [here](https://github.com/knowledge-for-good/knowledgeforgood/wiki/Linnea).

**Comment by avidrucker** [comment]
Marking as closed for now, please feel to reopen as needed.
