### ISSUE TITLE
What is the difference between an idea in discussions and an issue with the idea label?

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#189]
Asked by @seekanddefine 🌈

**Comment by avidrucker** [comment]
Why/rationale for making the "idea" label: By labeling an issue with the "idea" label, we can sort, search, autofocus, treeswipe, and make group decisions more effectively, I believe, on ideas.

Why/rationale for using discussions to discuss ideas: This gives us a more informal, casual, atmosphere where there isn't tracking, logging, or any pressure to answer where perhaps there might be a need to gain clarity, accessibility, and/or accountablity.

**Comment by seekanddefine** [comment]
I like it! Going to close now.
