### ISSUE TITLE
KFG Uploads after workshop chat video to get workshop feedback

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#190]
- [x] #191
- [x] #192

This is not for immediate public consumption, b/c we would like to share things we believe are helpful to a broader audience. KFG recording, uploading, and sharing is currently a WIP effort, where we are still figuring this out.

Context for idea label: "This is something I want to do, and I believe it could be helpful to KFG and it's audience."

**Comment by avidrucker** [comment]
@seekanddefine What do you believe is the value in this task (watching & uploading)? What might you like/hope to accomplish by watching & uploading?

**Comment by seekanddefine** [comment]
I'm going to go ahead and assign @avidrucker as you were interested in reviewing the feedback given at the end of the workshop that day. Let me know if there is any other way I can assist.

**Comment by avidrucker** [comment]
Temporarily pausing this.
