### ISSUE TITLE
What are the tradeoffs for us to use a repo wiki?

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#196]
Inspired by issue #72 

There may be UX / project management advantages or disadvantages to using the built in wiki pages feature of GitHub for a GitHub repository such as ours.

I'm curious how using a wiki might help or hinder us in our efforts to stay organized, maintain clarity and focus, and give us new capacities / efficiency in what it is that we do, such as:
- Plan projects
- Do time tracking
- Promote accessibility, accountability, and joy
- ... and more

On that note, I suggest we:
- [x] #197

**Comment by seekanddefine** [comment]
I'm going to close this for now. Notes can be found in #197. Feel free to reopen if needed.

**Comment by avidrucker** [comment]
@seekanddefine reflection is currently located here: https://github.com/knowledge-for-good/knowledgeforgood/issues/198
@avidrucker  reflection is currently located here: https://github.com/knowledge-for-good/knowledgeforgood/issues/199

**Comment by seekanddefine** [comment]
We did some research and then decided that the wiki wasn't the best place to organize research!
