### ISSUE TITLE
Linnea conducts research on GitHub wiki

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#198]
- [x] #202
- [x] Write down feedback on experience
- [x] #206

**Comment by seekanddefine** [comment]
### Cons:

*   _you don't get automatic notifications if the wiki is updated_
    *   [ways around this](https://stackoverflow.com/questions/8407917/how-can-you-track-or-be-notified-of-changes-to-github-wikis)
*   you cannot embed videos
*   GH doesn't support pull requests for wiki repositories

### Pros:

*   Can be exported into a PDF
*   Can write text in other formats like **AsciiDoc**, **RST** etc
*   Collaborative editing/preparing documents
*   Knowledge sharing
*   Can set permissions between users

### Examples:

*   Coding Style docs
*   Setup and Deployment procedures for web servers and sites
*   Network diagrams (what are all the servers in Dev, Staging, QA and Production called etc.)
*   Project docs (pdfs, visios, excel, docs, etc.) are stored in SVN. For the non-techies we have links to those docs in the wiki that point to an up-to-date share on my box. (tip: some wikis provide source control integration but ours doesn't)
*   Installation and Setup procedures for development tools
*   Howto's on things like using our bug tracking system, our unit testing philosophy
*   When doing research on a topic I often capture the important information in a wiki page for others to learn from
*   I've seen them used to keep seating charts in medium to large size organizations for the new people
*   At my previous company all of the emergency contacts and procedures for handling a critical outage where available on the front page of the wiki
*   The best part about a wiki is that it's searchable. Some wiki's support searching inside uploaded or linked docs as well.

If you setup a wiki and encourage or even require people to use it the amount of information that will accumulate can be amazing. It's definitely worth the effort especially if you have someone in IT with some spare time on their hands to set it up.

https://stackoverflow.com/questions/906917/what-are-some-examples-of-how-your-company-uses-a-wiki-for-development/907116#907116

**Comment by seekanddefine** [comment]
In what way or format should I share my experience? Should I just answer in text here and people interested can read it or should I share it at the next meeting or something else?

**Comment by avidrucker** [comment]
> In what way or format should I share my experience? Should I just answer in text here and people interested can read it or should I share it at the next meeting or something else?

I love how you shared your feedback here! I'm particularly excited and interested to share in 2 formats (audio and visual, or textual and video, etc.) to increase accessibility to more people (busy people, tired people, easily distracted people, people who may struggle to read text, etc..) On that note, I'd love to invite you to share once more, as you feel inspired 🌞 For now, feel free to close this issue since you've met the full request 👍🙂

**Comment by seekanddefine** [comment]
Final notes: Wiki will be good for non-techie communications but has limitations for collaboration because github doesn't have notifications for the wiki or pull requests. For now, it's better to use issues and research other options.
