### ISSUE TITLE
Collaborators learn how to "pause" issues

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#214]
Pausing is something I came up with one day. I realized that we had too many issues, and I thought, "It'd be nice if we could temporarily hide the issues we don't want to see." Filtering is the fastest and simplest way to do this, but, it requires a few minutes of learning and some practice to get the hang of. In the meanwhile, how about adding a "paused" label, assigning to the "icebox" milestone, and marking "closed" with a comment? So, that's what I've done. We can "unpause" issues as we need to, when we are ready.

## Steps to "Pause"
1. Add the "paused" label
2. Assign to the "icebox" milestone
3. Mark "closed" with a comment

**Comment by seekanddefine** [comment]
I like this very much and am ready to implement. I'm going to go ahead and close this for now. Thanks Avi!
