### ISSUE TITLE
KFG Invites friend to teach us about split mechanical keyboards

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#266]
- [x] #267
- [x] #268
- [x] #269
- [x] #270
- [x] #274
    - [x] #275
- [x] #276
    - [x] #277
    - [x] #278

**Comment by seekanddefine** [comment]
Did you already order wrist pads or should I go ahead and order @avidrucker

**Comment by seekanddefine** [comment]
Had a wonderful chat with Cameron and ordered the ergodox ez.

**Comment by avidrucker** [comment]
> Did you already order wrist pads or should I go ahead and order @avidrucker

Hi @seekanddefine , I was able to order wrist pads for myself. Did you still need wrist pads?

**Comment by seekanddefine** [comment]
I decided to use my roller mouse still, so I won't be getting wrist pads for now. Thanks!
