### ISSUE TITLE
Roughly how much time will it take to obtain "set up and working" status?

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#275]

**Comment by seekanddefine** [comment]
It sounds like six weeks is a good estimate from this review https://scarff.id.au/blog/2020/ergodox-ez-review/

**Comment by seekanddefine** [comment]
I also reviewed the links sent in the email upon purchase and have started playing with some layout ideas: Our [Getting Started](https://ergodox-ez.com/pages/getting-started) guide, full of good tips.

*   Our [configurator](https://configure.ergodox-ez.com/), called Oryx — get started with some layout ideas!
*   Our [YouTube channel](https://www.youtube.com/channel/UC4vLtltEorgqDkCMg6o0ioQ), containing lots of tutorials.
*   Our [return policy](https://ergodox-ez.com/pages/return-policy), just in case.
*   Our [support email](mailto:contact@ergodox-ez.com) — you can just write to say hi, too.
