### ISSUE TITLE
Members brainstorm names for tech non-for-profit / coop

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#43]
I did a 2 minute brainstorm just now. Please help me come up with more names, themes, or any other considerations you feel helpful / relevant: https://coggle.it/diagram/YNvRhXMy-XF1eQ-U/t/-/46106496fe0c9b83087370fe60ecf247b8ce844d8c722241cd1c0adce45681ce

**Comment by seekanddefine** [comment]
https://www.learn4good.com/ 

Learn 4 good is an interesting...job website?
