### ISSUE TITLE
Collaborators brainstorm on challenges/issues in education

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#50]
Original idea started here: Discussion #18 
Prompt: Share things here that you'd like to see improved / fixed / resolved
- [ ] Avi or Linnea creates a Coggle mindmap or other brainstorming document
- [ ] Person(s) above add mindmap/document links here

**Comment by seekanddefine** [comment]
We don't have a document for this, but these conversations are happening through MEET each week.
