### ISSUE TITLE
Research solutions for organizing research and resources on Github

### ISSUE THREAD

**Issue by seekanddefine** [knowledge-for-good/knowledgeforgood#51]
- [x] Curate research assets within a version control system
     - [x] Test create a Wiki entry 
     - [x] Test create a static page
- [x] Improve team work
- [x] #74
     - [x] Find examples of this in use
- [x] Structure repos to encourage high-quality contributions
- [x] Make better use of built-in project management tools like boards and milestones

**Comment by avidrucker** [comment]
> ### [About GitHub Education for educators and researchers](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/use-github-in-your-classroom-and-research/about-github-education-for-educators-and-researchers)
> @seekanddefine notes: Very basic, mostly links. See [how schools use Github Education](https://education.github.com/stories).

Could you add some context or a research query here, that we may convert to some sort of actionable? Not required, but it would be helpful I believe :)

**Comment by seekanddefine** [comment]
@avidrucker GitHub Education for educators and researchers is a landing page for people who are using GitHub Education specifically (not just normal GitHub). There is a classroom, a community, swagbags, and you can apply to GitHub Team for free.

**Comment by avidrucker** [comment]
> Watched [Organizing Work with GitHub webinar](https://resources.github.com/webcasts/Organizing-Work-with-GitHub-thankyou/).
> 
> ## Summary:
> Very basic and straightforward introduction to elements of GitHub with examples from real projects.
> 
> ## Reflection:
>  Much of this knowledge was not new to me and it didn't necessarily help me with new ideas, but key takeaways were:
> 
> -adhoc teams, consider using to help newbs to the project
> 
> -consider audience in documentation
> 
> -use pages with a click to generate static site, can be great for project-based updates and blogs
> 
> -wikis are repos, would like to look into this deeper, have questions about pushing updates from my personal github and think this may be a great way to organize research will look into further
> 
> ## Notes**:**
> Phil Holleran - GitHub Solutions Engineer (MN)
> 
> ### You’ll learn how to:
> * Organize your teams to provide appropriate access and improve the flow of information
> * Effectively categorize, visualize, and sort works-in-progress
> * Structure repositories to encourage high-quality contributions
> * Use GitHub’s project management tools like project boards and milestones
> 
> I prefer videos where I can speed up the audio!
> 
> Apply organizational principles to
> 
> 1. People-collaboration
>    
>    1. Starts with teams
>       
>       1. mapped to org chart
>       2. adhoc by interests
>    2. Mapping permission - read/write
>    3. Adhoc teams are recommended (not just devGroups)
>       
>       1. Could be policy related, security, marketing, design, or anything tangential
>       2. matrix organization
>    4. Use @mention teams
>    5. can observe and learn from others
>    6. offer expertise/assistance to those who ask
>       
>       1. great for new developers to lurk/learn
> 2. Repositories
>    
>    1. Documentation
>       
>       1. Consider audiences
>          
>          1. Contributors maintaining codebase
>             
>             1. How does the code work
>             2. How do I contribute
>             3. Where do I go to modify and do what I need to do
>          2. Enduser
>             
>             1. How to I grab the library and integrate it?
>             2. How do I install and get started?
>          3. General Public
>             
>             1. Anyone who wants to know
>             2. Intranet vs. Internet
>       2. README.md
>          
>          1. Drop in contributor documentations
>          2. Install instructions
>          3. README is rendered at every level of the project
>          4. Drop directly in docs folder to put documentation directly into the code to keep up-to-date with codebase
>       3. GitHub pages
>          
>          1. static site and reader doesn't require any coding to generate
>          2. Can produce multiple page sites/pagination (Ex. Atom Flight Manual)
>          3. Facebooks ex: blogs, posts, devops/infastructure blogs, marketing, hr, event promotion, hiring posts
>       4. Wiki
>          
>          1. Created through UI
>             
>             1. ex. Netflix Hystrix Wiki
>             2. Wikis are Git repos in and of themselves
>                
>                1. clone to local machine
>                2. work on,
>                3. push changes
>    2. Contributions
>       
>       1. Contributing.md
>          
>          1. Notifies folx with a yellow bar
>          2. Good ex. Electron
>       2. Support.md
>          
>          1. especially good if you are using external bug tracking
>       3. Templates
>          
>          1. Issue_template.md
>          2. pull_request.md
>    3. Contributions
>       
>       1. how to encourage quality
>    4. Topics to group repos
>       
>       1. will be displayed at top of repo and sort repos by topic and by team
>       2. releases
>    5. Releases to manage end product
>       
>       1. tag any point in history
>          
>          1. share compiled binaries (?)
>          2. look at code as it existed in history
> 3. Organize Tasks
>    
>    1. Task lists
>       
>       1. Markdown todo lists in an issue
>       2. Issues show states and show how close you are to finishing ex. 5 of 5
>    2. Labels
>       
>       1. Great models ex. Electron
>          
>          1. code by color and by text
>             
>             1. salmon - components
>             2. red - bugs
>          2. visually determine amount in a glass
>       2. Webhook events (?)are driven directly off labels
>          
>          1. Apply a label to trigger an event to notify other systems
>          2. Logic is taken care of outside of it through chained events integrating systems through automation
>    3. Milestones
>       
>       1. Group together pull requests and issues in a like unit and assign it a due date
>       2. In agile environment can track sprints
>          
>          1. flow built in
>    4. Projects
>       
>       1. Uses cards and columns
>       2. Exist in repository level or org level
>       3. Visual work
>          
>          1. drag cards between columns
>          2. track activity history
>          3. filter and search cards
>             
>             1. ex. author:

Do you know if a visual mindmap can be made quickly ala copy-paste or import from nested lists like these? I'd love to see this visualized on a Coggle board or similar, with pictures or diagrams. Something like this could be really cool:

![visual mindmap](https://www.mindmeister.com/blog/wp-content/uploads/2019/04/MindMapping_mindmap_handdrawn-796x531.png)

**Comment by avidrucker** [comment]
> ### [How to setup GitHub for a research project from UCL](https://www.ucl.ac.uk/isd/how-to/how-to-setup-github-for-research-project)
> Private repositories are free for non-profit research.
> 
> Can have up to 20 repos.
> 
> Will need to upload proof.

What kind of proof is required? I will make an issue for this 🙂

**Comment by avidrucker** [comment]
Hi there @seekanddefine , do you feel that the 30 min time estimate captures roughly the time on this task? For time keeping purposes, I encourage you to update the time estimate after the fact if it took significantly more (2x+) time than you originally estimated.

**Comment by avidrucker** [comment]
> @avidrucker GitHub Education for educators and researchers is a landing page for people who are using GitHub Education specifically (not just normal GitHub). There is a classroom, a community, swagbags, and you can apply to GitHub Team for free.

That context is very helpful and clear, thank you 🌞
