### ISSUE TITLE
Create a readme.md for KFG repo.

### ISSUE THREAD

**Issue by seekanddefine** [knowledge-for-good/knowledgeforgood#52]

**Comment by avidrucker** [comment]
I will mark this issue as closed since I just made the first draft. I will make a new issue now to review & improve it with feedback from our other half 😉

**Comment by avidrucker** [comment]
Also, @seekanddefine I apologize, I accidentally took action on this even though you assigned yourself. I will take care to make sure I am not accidentally repeating work or taking away work that you would prefer to do.
