### ISSUE TITLE
Do we need / want a YouTube channel for KFG videos (such as our workshops, learn in public recordings, etc.)?

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#55]

**Comment by seekanddefine** [comment]
I set one up before I saw this!   [https://www.youtube.com/channel/UCkynv82S4xOnQsdQRlOELoQ](https://www.youtube.com/channel/UCkynv82S4xOnQsdQRlOELoQ)

https://coggle.it/diagram/YPjWGpZ6Qt1H8oYP/t/-

**Comment by seekanddefine** [comment]
I'm not sure if I should close this now since it has an open mindmap in it

**Comment by caryfado** [comment]
I can't mark this completed.

**Comment by avidrucker** [comment]
> I'm not sure if I should close this now since it has an open mindmap in it

Sorry for the late reply! We can add a label "has-mindmap" and close for now 👍🙂

**Comment by avidrucker** [comment]
> I can't mark this completed.

Thank you for letting me know! Context: This is from when we set up your permissions 🌞
