### ISSUE TITLE
What is our process to add videos to Youtube?

### ISSUE THREAD

**Issue by seekanddefine** [knowledge-for-good/knowledgeforgood#57]
- [x] #159
- [x] #160
- [x] #161
- [x] #162
- [x] #163

**Comment by seekanddefine** [comment]
Related to #84 and #85

**Comment by seekanddefine** [comment]
We now have Knowledge for Good on youtube as a shared creator space and I put a time on the Calendar for Thursday for an OBS session. Let me know if that works!

**Comment by avidrucker** [comment]
> @avidrucker What are you suggestions?
> 
> 1.  Determine at the beginning of meeting who will record.
> 2.  Determine how notes will be saved. Default to saving in a source that doesn't disappear (meeting chat disappears).
> 3.  Record video
>     1.  What program?
>         1.  **OBS-Free and Opensource**
>         2.  Zoom-Free options
>         3.  Loom-Free options
>         4.  Wondershare DemoCreator
> 4.  Save video
>     1.  What is a good way to organize videos?
>     2.  What is a good way to store videos?
> 5.  Upload to Youtube
>     1.  What account do we use to upload to youtube?

Let's capture these questions into issues, or address in a call and capture our answers, pretty please! 🙂

**Comment by avidrucker** [comment]
Context for reopening is that we have open questions. I believe we would stand to benefit greatly by making clear our process, and making an effort to answer our open questions. In the meanwhile, we have already recorded a number of videos which are up on our [KFG YouTube channel](https://www.youtube.com/channel/UCkynv82S4xOnQsdQRlOELoQ)
