### ISSUE TITLE
(re) Learn OBS together

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#61]

**Comment by seekanddefine** [comment]
How could we better time chunk this issue? I put a one hour collab time on the calendar, but we aren't going to learn all of OBS in one hour?

**Comment by avidrucker** [comment]
> How could we better time chunk this issue? I put a one hour collab time on the calendar, but we aren't going to learn all of OBS in one hour?

@seekanddefine I updated the issue name to clarify & constrain the issue goal, and I broke down the issue into suggested sub-goals, with the intent to encourage exploration (using goalposts without explicit "how-to" steps). I think 30 minutes should be enough to make some headway on this, how about you?
