### ISSUE TITLE
Categorize, visualize, sort WIP

### ISSUE THREAD

**Issue by seekanddefine** [knowledge-for-good/knowledgeforgood#74]

**Comment by avidrucker** [comment]
@seekanddefine Is this issue still in-progress / relevant / helpful ?

**Comment by seekanddefine** [comment]
I created a Wiki sidebar to help us organize projects, meetings, milestones, and member contributions. I am closing this for now.

![](https://user-images.githubusercontent.com/38668794/127661968-2c84f223-fbfc-441a-8eb6-187b716fa4e1.png)

**Comment by avidrucker** [comment]
> @seekanddefine Is this issue still in-progress / relevant / helpful ?

I'm sorry I'm just seeing this issue now. What was the original context of "Categorize, visualize, sort WIP" (ie. what was "WIP" referring to?)
