### ISSUE TITLE
Linnea sets up work station that improves ergonomics

### ISSUE THREAD

**Issue by seekanddefine** [knowledge-for-good/knowledgeforgood#82]
[ ] How to add a monitor to the squat setup?

**Comment by avidrucker** [comment]
How about we get you a 2nd 2nd monitor? :wink:

**Comment by seekanddefine** [comment]
I'm still not sure what my next step is here.

Possible options:

*   Finding/purchasing a monitor
*   Finding keyboard mouse in garage and purchasing a keyboard to go with it to help hand/arm pain.
*   Creating/purchasing desk that goes from squat to stand easily and quickly.
*   ?

**Comment by avidrucker** [comment]
I encourage you to get the squat chair, and I'll grab a monitor for you. The keyboard and a mouse are vital probably as well. Do you know any physical/occupational therapists who could advise us?

**Comment by avidrucker** [comment]
@seekanddefine Would you send me the link of the monitor you'd like to get? I can expense it for us and ship it to you. Or if you prefer, you can purchase and then invoice me.

**Comment by avidrucker** [comment]
Are there any blockages?

**Comment by seekanddefine** [comment]
Working on this right now.

**Comment by seekanddefine** [comment]
Update. I tried using the TV but the pixels did not look good and it has a crack in the screen, so that's a little bit annoying. Right now I'm loving squatting at my bed and in the yoga room. I am thinking this week about how to set up an external monitor in this arrangement but am don't have any tables that are the right height. That means I might look at the thrift store and then cut the legs off or see if I can find something adjustable, maybe modifying a sit to stand that would be on a desk? The other dilemma is that my mouse only works on an external keyboard and so it's not ideal using it with my laptop keyboard which I much prefer typing on. My current keyboard has a couple sticky spots and the keys themselves are not the best ergonomically because I need to lift my fingers up higher.  The squatting is going AMAZING!  Love it so much and alternate between different heights and cushions throughout the day. Really excited about this improvement.

**Comment by seekanddefine** [comment]
Feeling great about my current setup. Am looking forward to the keyboard which will help with wrist and finger pain. Closing for now!
