### ISSUE TITLE
Avi sets up work station that improves ergonomics

### ISSUE THREAD

**Issue by seekanddefine** [knowledge-for-good/knowledgeforgood#83]

**Comment by avidrucker** [comment]
I'll go with the standing desk for now :+1:

**Comment by avidrucker** [comment]
Updates:
- I added a pillow to my sitting desk
- I set up my standing desk! 😄
- I use my yoga mat now to make my feet more comfy with my standing desk

**Comment by avidrucker** [comment]
Marking as closed, as I feel that my setup is (markedly improved and) sufficiently ergonomic for now. That said, I am eyeing those mechanical split keyboards... ⌨👀😁
