### ISSUE TITLE
All collaborators learn how to record video & audio on all of their devices

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#84]
So we can share our learning & collaboration consistently

- [ ] Learn which tools allow for, and how to, add time-stamps while recording
- [ ] Take a look through the webs and GitHub for "open source" resources for creators

**Comment by seekanddefine** [comment]
1.  Write timestamps on piece of paper
2.  OBS Studio + Infowriter : [https://www.youtube.com/watch?v=CWS8jQzDdvs&ab_channel=Swxade](https://www.youtube.com/watch?v=CWS8jQzDdvs&ab_channel=Swxade)
    1.  OBS is recommended for open source video creation, especially tutorials
    2.  Screen capture is the first element. "Scenes" and "sources" are used. Inset webcams can be added. 
    3.  OBS recursively captures itself. 
3.  OpenShot is an open source video editor. Both OBS and OpenShot are programmed in Qt and available on multiple operating systems. 
4.  Audacity is great and what I would recommend for audio editing. 

Article: [3 open source tools for producing video tutorials](https://opensource.com/article/21/3/video-open-source-tools)

**Comment by avidrucker** [comment]
> 1.  Write timestamps on piece of paper
> 2.  OBS Studio + Infowriter : [https://www.youtube.com/watch?v=CWS8jQzDdvs&ab_channel=Swxade](https://www.youtube.com/watch?v=CWS8jQzDdvs&ab_channel=Swxade)
>     1.  OBS is recommended for open source video creation, especially tutorials
>     2.  Screen capture is the first element. "Scenes" and "sources" are used. Inset webcams can be added. 
>     3.  OBS recursively captures itself. 
> 3.  OpenShot is an open source video editor. Both OBS and OpenShot are programmed in Qt and available on multiple operating systems. 
> 4.  Audacity is great and what I would recommend for audio editing. 
> 
> Article: [3 open source tools for producing video tutorials](https://opensource.com/article/21/3/video-open-source-tools)

May we break these numbered items into contextualized groups such as "tools", "stories", or, "investigate these" ?
