### ISSUE TITLE
Epic issue of questions to find answers for

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#87]
From this discussion: https://github.com/knowledge-for-good/knowledgeforgood/discussions/20#discussioncomment-940057

My intention is to foster exploration and resolution of as many of these questions as we can, in as transparent of a way as possible.

**Comment by seekanddefine** [comment]
See #97 #96 #95 #94 #93 #92 #91

**Comment by avidrucker** [comment]
Reopening as I believe this is a useful epic to keep our eyes on ;)

**Comment by avidrucker** [comment]
How does answering any of these questions help us move towards registering?

**Comment by avidrucker** [comment]
How do we make async decisions?

**Comment by avidrucker** [comment]
What happens if we don't agree on a point?

**Comment by avidrucker** [comment]
I will move these bottom three questions out of here and into their own individual issues.

**Comment by avidrucker** [comment]
I'd like very much for us to put some time on the calendar. I intend to do so today. I think this will up our motivation & help us determine which questions are particularly pressing & which ones perhaps we can archive or postpone.
