### ISSUE TITLE
Q1: Should every employee be paid the same?

### ISSUE THREAD

**Issue by seekanddefine** [knowledge-for-good/knowledgeforgood#91]
Q1: Should every employee be paid the same?

A1:Research tech co-op networks/supports  
\-There are some co-ops working together to found collective marketing groups with cooperative values  
\-start-up accelerators may also provide valuable resources, mentor pairing, crowdfunding session to raise seed funding  
\-cooperative banks  
\-using "community shares": can't be sold for-profit, withdrawable and upon which fixed interest in profitable years  
\-"sweaty equity" recording volunteer hours to be paid back later

**Comment by avidrucker** [comment]
If we can codify in clear, plain language a "minimum payable chunk" for example:
- 30 minutes
- 1 task of X complexity
- "not easily quantifiable but greatly appreciated contribution"

The hope here is that, we can log publicly what we do, and compensate people for contributing. I personally would rather us not do hourly, and rather do by/per task, but also say, investment of time also matters. The intention here is that, we can help people focus on contributing to the best of their ability, compensate them for their valuable time, energy, and skills, without saying, we're merely paying for time or only paying for X results.

**Comment by avidrucker** [comment]
In short, my answer is yes... and, if people want to, for example, do skill/service trades instead of being paid. @seekanddefine Do you have more insight into what our main options are?

**Comment by avidrucker** [comment]
> -There are some co-ops working together to found collective marketing groups with cooperative values
> -start-up accelerators may also provide valuable resources, mentor pairing, crowdfunding session to raise seed funding
> -cooperative banks
> -using "community shares": can't be sold for-profit, withdrawable and upon which fixed interest in profitable years
> -"sweaty equity" recording volunteer hours to be paid back later

Are these options or choices for us to pick from?

**Comment by avidrucker** [comment]
I would love us to do some further research or brainstorming or discussion on this to find a satisfying path forward that we can all consent to enthusiastically.
