### ISSUE TITLE
Are all questions deserving of answers?

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#98]
The context here, I believe, is that everyone has different amounts of curiosity, interest, different needs, and different focuses. Depending on who needs what when, different kinds of questions, with varying specificity may arise. How can we make the time & presence available to those in need of answers, while also gently affirming that, we might not have the answers, the time, or the patience to answer *all* questions.

**Comment by seekanddefine** [comment]
Compassionate questions are worth considering, but I'm not sure that anything deserves an answer just because it was asked.

**Comment by avidrucker** [comment]
> Compassionate questions are worth considering

What distinguishes a compassionate question from one that is not? 🙂
